const express = require('express');
const router = express.Router();
const Issue = require('../models/issue');
const ObjectId = mongoose.Types.ObjectId;

/**
 * @api {post} /api/issues Create an issue
 * @apiName CreateIssue
 * @apiGroup Issue
 * @apiVersion 1.0.0
 * @apiDescription Registers a new issue.
 *
 * @apiUse IssueInRequestBody
 * @apiUse IssueInResponseBody
 * @apiUse IssueValidationError
 * @apiSuccess (Response body) {String} id A unique identifier for the issue generated by the server
 *
 * @apiExample Example
 *     POST /api/issues HTTP/1.1
 *     Content-Type: application/json
 *
 *     {
 *      //
 *     }
 *
 * @apiSuccessExample 201 Created
 *     HTTP/1.1 201 Created
 *     Content-Type: application/json
 *
 *     {
 *     }
 */
router.post('/', utils.requireJson, function(req, res, next) {
  new Issue(req.body).save(function(err, savedIssue) {
    if (err) {
      return next(err);
    }

    debug(`Created issue "${savedIssue.description}"`);

    res
      .status(201)
      .set('Location', `${config.baseUrl}/api/issues/${savedIssue._id}`)
      .send(savedIssue);
  });
});



/* GET issues listing. */
router.get('/', function(req, res, next) {
  res.send('respond with a resource');
});

module.exports = router;
